apiVersion: v1
kind: Service
metadata:
  name: node-kube-app-service
spec:
  selector:
    app: node-kube-app # Selects Pods with this label
  ports:
    - protocol: TCP
      port: 80       # The port the Service itself will listen on
      targetPort: 8000 # The port your application container is listening on (EXPOSEd in Dockerfile)
  type: NodePort # Or NodePort/ClusterIP depending on your need
                     # LoadBalancer is common for external access in cloud K8s
                     # NodePort if using minikube or need to access via node IP:port
