
#output
kind: Pod
apiVersion: v1
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: task-pv-volume
      persistentVolumeClaim:
       claimName: claim-mysql
  containers:
    - name: task-pv-container
      image: docker.io/nginx:run
      ports:
        - containerPort: 80
          name: "http-server"
            #volumeMounts:
            #- mountPath: "/usr/share/nginx/html"
            #name: task-pv-storage

